### ISSUE TITLE
What's Kin's bucket hostname?

### ISSUE THREAD

**Issue by chancity** [kinecosystem/stellar-dashboard#5]
I see you're parsing data files to reteive the operations occurring on the stellar blockchain. 

```
# Constants:
BUCKET_NAME = 'history.stellar.org'
CORE_DIRECTORY = 'prd/core-testnet/core_testnet_001/'
```

What's Kin's bucket_name hostname and core directory?

**Comment by Ronserruya** [comment]
For ecosystem(Main):
BUCKET_NAME = 'stellar-core-ecosystem-6145'
CORE_DIRECTORY = ''

For playground(Test):
BUCKET_NAME = 'stellar-core-playground-55a3'
CORE_DIRECTORY = ''

you can view/download the files with aws cli
```aws s3 --no-sign-request ls s3://stellar-core-ecosystem-6145/```
